### PR TITLE
Update Long-run Growth

### PR DESCRIPTION
**Pull request by HumphreyYang**
Hi @mmcky, 

I have updated a new version of long-run growth. 

There are some thoughts going into this lecture.

I have to create a Country Code -> Chinese name mapping to print Chinese in the graphs and in the function, so I have to change some of the code in the lecture. 

CC @longye-tian @SylviaZhaooo if you need to have a mapping from a 3-letter country code to a Chinese country name.

### CODE REVIEW

**Comment by HumphreyYang** [comment]
Hi @mmcky, to show Chinese on my Linux machine, I have to add `SimHei.ttf` to the mpl directory (i.e.,

/home/humphrey/anaconda3/envs/quantecon/lib/python3.1/site-packages/matplotlib/mpl-data/fonts/ttf

)

**Comment by HumphreyYang** [comment]
Hi @mmcky,

I have uploaded the font according to your suggestions. We can propagate these lines to other lectures once this is merged : )

**Comment by mmcky** [comment]
thanks @HumphreyYang

**Comment by HumphreyYang** [comment]
Hi @mmcky,

Would you mind if I merge this for now? I think it builds and looks good. It will help me build previews for other PRs.

Many thanks in advance.

**Comment by mmcky** [comment]
thanks @HumphreyYang

**Pull request merged**
