### PR TITLE
[intro_supply_demand] Translation 

### PR DESCRIPTION
**Pull request by longye-tian**
Hi all, @mmcky, @HumphreyYang , @SylviaZhaooo 

I have finished the translation of intro_supply_demand.md and put it into the folder of lecture.

Best,
Longye

### CODE REVIEW

**Comment by mmcky** [comment]
@longye-tian not sure why your translated version wasn't in the preview. So I closed and re-opened this issue to get a fresh build.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

Is it because of the file name has '_cn'?

**Comment by mmcky** [comment]
> Hi @mmcky,
> 
> Is it because the file name has '_cn'?

Ah Of course! thanks @HumphreyYang -- end of the day tired brain. 

@longye-tian once that is renamed and pushed then it should build just fine.

**Comment by HumphreyYang** [comment]
No worries! Have a nice rest : )!

**Comment by mmcky** [comment]
@longye-tian I updated the file name in this PR to trigger a new build to make sure all is working on the GitHub Actions side.

**Comment by mmcky** [comment]
@longye-tian I can jump into this tomorrow but it looks like there are a few missing equation links

```
/home/runner/work/lecture-intro.zh-cn/lecture-intro.zh-cn/lectures/intro_supply_demand.md:442: WARNING: equation not found: eq:cstm_spls
writing output... [100%] zreferences                                           
/home/runner/work/lecture-intro.zh-cn/lecture-intro.zh-cn/lectures/intro_supply_demand.md:505: WARNING: equation not found: eq:pdcr_spls
/home/runner/work/lecture-intro.zh-cn/lecture-intro.zh-cn/lectures/intro_supply_demand.md:561: WARNING: equation not found: eq:old1
/home/runner/work/lecture-intro.zh-cn/lecture-intro.zh-cn/lectures/intro_supply_demand.md:578: WARNING: equation not found: eq:old1
/home/runner/work/lecture-intro.zh-cn/lecture-intro.zh-cn/lectures/intro_supply_demand.md:581: WARNING: equation not found: eq:old1
/home/runner/work/lecture-intro.zh-cn/lecture-intro.zh-cn/lectures/supply_demand_multiple_goods.md:618: WARNING: equation not found: eq:old1
```

**Comment by mmcky** [comment]
- [x] added this bug note to https://github.com/QuantEcon/lecture-intro.zh-cn/wiki/General-Rules-for-Improved-Translations#bugs

**Comment by mmcky** [comment]
thanks @longye-tian. 

@longye-tian and @SylviaZhaooo when you have time if you can please update your PRs so that

1. filename excludes the `_cn` and replaces the `md` file in `lectures` folder
2. check builds for any failures.

**Pull request merged**
