### PR TITLE
[laffer_adaptive] Update translations of the term

### PR DESCRIPTION
**Pull request by SylviaZhaooo**

### CODE REVIEW

**Comment by mmcky** [comment]
@SylviaZhaooo it looks like this PR is using a previous branch name for the translation that you have updated. 

Are you able to resolve this conflict? Happy to help if need it.

**Comment by mmcky** [comment]
@SylviaZhaooo let me know if you need help re: resolving this conflict as the diff is showing git markup which suggests the conflict is outstanding. Thanks.

**Comment by SylviaZhaooo** [comment]
Hi @mmcky,

I've made some further updates to the markdown file. Could you please check if everything looks good now?

**Comment by mmcky** [comment]
thanks @SylviaZhaooo

**Pull request merged**
